// frontend/react/src/FeaturesList.js
const React = require('react')
require('./FeaturesList.css');

const FeaturesList = (props) => {

  const features = props.features.map((feature, index) => {
    return (
    <ul key={index}>
      <li>
        <h3>{feature.name}</h3>
        <p>{feature.description}</p>
        <a href={feature.MDNLink}>Documentation 📖</a>
        <h5>{feature.isFullyImplemented ? "Fully Implemented ✅": "Please implement me here 👇"}</h5>
        <code>{feature.implementations}</code>
        <p></p>
      </li>
    </ul>
    )
  })

  return (
  <div>
    {features}
  </div>
  )


}

module.exports = FeaturesList

// frontend/vue-es6/src/components/FeaturesList.vue
<template>
  <div class="hello">
    <ul v-for="(feature, index) in features" :key="index">
      <li>
        <h3>{{feature.name}}</h3>
        <p>{{feature.description}}</p>
        <a href="feature.MDNLink">Documentation 📖</a>
        <h5>{{feature.isFullyImplemented ? "Fully Implemented ✅": "Please implement me here 👇"}}</h5>
        <code>{{feature.implementations}}</code>
        <p></p>
      <li/>
    </ul>
  </div>
</template>

<script>
export default {
  name: 'FeaturesList',
  props: ['features']
}
</script>

<style scoped>
  ul {
  list-style: none;
  border: 1px solid black;
}
</style>
