// frontend/react-end/src/FeaturesList.js
import React from 'react'
import('./FeaturesList.css');

const FeaturesList = ({ features }) => {

  const featuresLists = features.map((feature, index) => {
    const {name, description, MDNLink, isImplemented, implementations} = feature
    return (
    <ul key={index}>
      <li>
        <h3>{name}</h3>
        <p>{description}</p>
        <a href={MDNLink}>Documentation 📖</a>
        <h5>Implemented? {isImplemented ? "✅": "❌"}</h5>
        <p>Possible Implementations:</p> 
        <p><code>{implementations}</code></p>
      </li>
    </ul>
    )
  })

  return (
  <div>
    {featuresLists}
  </div>
  )


}

export default FeaturesList

// vue_es6_comparison/src/components/FeaturesList.vue
<template>
  <div>
    <ul v-for="(feature, index) in features" :key="index">
      <li>
        <h3>{{ feature.name }}</h3>
        <p>{{ feature.description }}</p>
        <a :href="feature.MDNLink">📖 Documentation</a>
        <h5>Implemented? {{ feature.isImplemented ? "✅": "❌"}}</h5>
        <p>Implementations:</p> 
        <p><code>{{ feature.implementations }}</code></p>
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  name: 'FeaturesList',
  props: ['features']
}
</script>

<style scoped>
  ul {
    list-style: none;
    border: 1px solid black;
  }
</style>
